version: "3.1"

services:
  postgres:
    image: postgres
    container_name: base-a-pg
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: teste
    volumes:
      - ./databases/postgres/data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bridge-network
  mongo:
    image: mongo
    container_name: base-b-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
    volumes:
      - ./databases/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - bridge-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_URL: mongodb://root:teste@mongo:27017/
    depends_on:
      - mongo
    networks:
      - bridge-network
  elasticsearch:
    container_name: base-c-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    volumes:
      - ./databases/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - bridge-network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.1
    restart: unless-stopped
    ports:
      - 5601:5601
    networks:
      - bridge-network

  busca-dados-consumidores:
    build: ./apps/busca-dados-consumidores/
    container_name: bdc
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./apps/busca-dados-consumidores/:/var/www
    networks:
      - bridge-network
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./apps/busca-dados-consumidores/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: "bridge"
    name: bridge-network
